### ISSUE TITLE
Running the example failed

### ISSUE THREAD

**Issue by aaashift** [YangLab/RNAlight#1]
Run the "_**RNAlight -q $RNAlight/example/query.fasta -p Test -o RNAlight_Test**_" command, the program throws the following error:
Traceback (most recent call last):
  File "/home/zhaobaoying/work/RNAlight/RNAlight", line 177, in <module>
    y_pred = RNA_Light.predict(x_kmer)
  File "/home/zhaobaoying/anaconda3/envs/RNAlight/lib/python3.6/site-packages/lightgbm/sklearn.py", line 870, in predict
    pred_leaf, pred_contrib, **kwargs)
  File "/home/zhaobaoying/anaconda3/envs/RNAlight/lib/python3.6/site-packages/lightgbm/sklearn.py", line 923, in predict_proba
    pred_leaf, pred_contrib, **kwargs)
  File "/home/zhaobaoying/anaconda3/envs/RNAlight/lib/python3.6/site-packages/lightgbm/sklearn.py", line 680, in predict
    X = _LGBMCheckArray(X, accept_sparse=True, force_all_finite=False)
  File "/home/zhaobaoying/anaconda3/envs/RNAlight/lib/python3.6/site-packages/sklearn/utils/validation.py", line 582, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 1344)) while a minimum of 1 is required.

**Comment by aaashift** [comment]
@Yuangaga I hope you can reply to the question. Thank you!

**Comment by aaashift** [comment]
I hope you can reply to the question. Thank you! @YangLab

**Comment by aaashift** [comment]
I hope you can reply to the question. Thank you! @Yuangaga

**Comment by Yuangaga** [comment]
> Run the "_**RNAlight -q $RNAlight/example/query.fasta -p Test -o RNAlight_Test**_" command, the program throws the following error: Traceback (most recent call last): File "/home/zhaobaoying/work/RNAlight/RNAlight", line 177, in y_pred = RNA_Light.predict(x_kmer) File "/home/zhaobaoying/anaconda3/envs/RNAlight/lib/python3.6/site-packages/lightgbm/sklearn.py", line 870, in predict pred_leaf, pred_contrib, **kwargs) File "/home/zhaobaoying/anaconda3/envs/RNAlight/lib/python3.6/site-packages/lightgbm/sklearn.py", line 923, in predict_proba pred_leaf, pred_contrib, **kwargs) File "/home/zhaobaoying/anaconda3/envs/RNAlight/lib/python3.6/site-packages/lightgbm/sklearn.py", line 680, in predict X = _LGBMCheckArray(X, accept_sparse=True, force_all_finite=False) File "/home/zhaobaoying/anaconda3/envs/RNAlight/lib/python3.6/site-packages/sklearn/utils/validation.py", line 582, in check_array context)) ValueError: Found array with 0 sample(s) (shape=(0, 1344)) while a minimum of 1 is required.

It seems that the input sequence is incorrect. In the RNAlight/example directory, the specific name of the query sequence is "Query.fa". Therefore, you can try modifying the command from "RNAlight -q $RNAlight/example/query.fasta -p Test -o RNAlight_Test" to "**RNAlight -q /home/zhaobaoying/work/RNAlight/example/Query.fa -p Test -o RNAlight_Test**". This modification may allow the command to work properly.

**Comment by aaashift** [comment]
Thank you for your reply. But I did, and it was the same error. @Yuangaga

**Comment by aaashift** [comment]
Thank you for your reply. I did so, but the same error message still appeared

**Comment by aaashift** [comment]
Thank you for your reply. I did so, but the same error message still appeared

**Comment by Yuangaga** [comment]
When I uninstalled “**seqkit**”, I encountered the same issue you are having. I think this issue would be resolved by installing “seqkit” using the command “**conda install seqkit=0.14.0**”, as mentioned in the section “**1.3 RNAlight Conda setup**”. I hope this can help you.

**Comment by aaashift** [comment]
Thanks, problem solved!
